### ISSUE TITLE
riscv-qemu PMP function revise

### ISSUE THREAD

**Issue by wxjstz** [riscv/riscv-qemu#172]
I tried to test the PMP function of qemu and passed my test case. But I found that the mainline code has been updated and I tried to merge failed.

My code is located at: https://github.com/wxjstz/riscv-qemu/tree/qemu-for-testing.pmp

**Comment by michaeljclark** [comment]
I've merged your changes and my changes here:

- https://github.com/riscv/riscv-qemu/tree/qemu-for-upstream

I've rolled back some of my changes and included several of yours. I don't think we need to scan twice for the TLB fix, instead we can pass both the request size and the TLB size (inout), and adjust the TLB size down if the matches rule is smaller than the initial TLB size (PAGE_SIZE), given the priority and rule matching logic dictates the first matching rule must be selected, we know that if the rule is within the the boundaries of a page, then we must return a smaller TLB size. Also we can short-circuit given we correctly handle discontiguous rules.

These branches are stable, and only move forward, so if you base patches on these branches, then you won't get merge failures, however they are behind:

- https://github.com/riscv/riscv-qemu/tree/master # _QEMU upstream_
- https://github.com/riscv/riscv-qemu/tree/riscv-qemu-3.0 # _QEMU 3.0 backport branch_
- https://github.com/riscv/riscv-qemu/tree/riscv-qemu-2.12 # _QEMU 2.12 backport branch_

These branches are future, due to the nature or upstream, such as the need to add Reviewed-by and Signed-off-by, these branches will be rebased to incorporate patch review feedback and rebase against upstream changes:

- https://github.com/riscv/riscv-qemu/tree/qemu-for-testing # _still requires further testing_
- https://github.com/riscv/riscv-qemu/tree/qemu-for-upstream # _ready to send upstream_
- https://github.com/riscv/riscv-qemu/tree/riscv-all # _integration of testing and for-upstream_

We need more open source test cases. If you can share some that would be great!
