### ISSUE TITLE
Is it possible to use more than one block device?

### ISSUE THREAD

**Issue by manuelafm** [riscv/riscv-qemu#18]
Hi,

I tried to use more than one -drive, or -cdrom or -hdb, but it doesn't seem to work.

Is it possible to have more than one block device at all?

**Comment by sagark** [comment]
The HTIF block device doesn't allow this at the moment. I'm not currently planning on adding support for this to the HTIF device since HTIF is being phased out anyway. This should be doable with other block devices that QEMU supports, but I haven't had a chance to try it yet.

Better general device support will probably come once QEMU is updated to the new 1.9 privileged spec and the platform spec starts to stabilize.

**Comment by manuelafm** [comment]
OK, thanks for the info!
