### ISSUE TITLE
errno=Connection refused; Firewall blocks git:// 

### ISSUE THREAD

**Issue by gojimmypi** [riscv/riscv-qemu#189]
Some firewalls will block ports used by  `git://` with `git clone` returning an unintuitive `errno=Connection refused` error message like this:

```
Submodule 'riscv-qemu' (git://github.com/riscv/riscv-qemu.git) registered for path 'riscv-qemu'
Cloning into 'riscv-qemu'...
fatal: unable to connect to github.com:
github.com[0: (my IP)]: errno=Connection refused
github.com[1: (my IP)]: errno=Connection refused

Clone of 'git://github.com/riscv/riscv-qemu.git' into submodule path 'riscv-qemu' failed
make[1]: *** [build-riscv32i-tools-bh] Error 1
make[1]: Leaving directory `/home/gojimmypi/workspace/picorv32'
make: *** [build-tools] Error 2
```

One possible solution:

`git config --global url.https://github.com/riscv.insteadOf git://github.com/riscv`

I'm curious: why not always use `https://` ?

edit: see also: https://github.com/cliffordwolf/picorv32/issues/106

**Comment by jim-wilson** [comment]
These github riscv packages are maintained by a lot of different people, and getting everyone to agree on one convention is infeasible.  Also, a lot of the people working with these projects don't fully understand how git submodules work.  They just use them.  When I find ssh: references I fix them, but I'm not going to worry about https versus git.  Using insteadOf is what we recommend when people run into trouble.

FYI This project is not being actively maintained at present.  I would suggest using upstream qemu instead of this one, unless perhaps you need the support for separate bbl/vmlinux which is only here at the moment, though we are trying to get it upstream.  All of the real riscv qemu work is happening upstream now.

**Comment by gojimmypi** [comment]
understood. thanks
